import {
  fStatusMarketHNX,
  fStatusMarketHSX,
  fStatusMarketUPCOM,
} from "../../../utils/util";
import {
  HNX,
  HNX30,
  HNXCON,
  HNXFIN,
  HNXLCAP,
  HNXMAN,
  HNXSMCAP,
  UPCOM,
  VN100,
  VN30,
  VNALL,
  VNI,
  VNMID,
  VNMSL,
  VNXALL,
} from "./className";
import {
  IRecieve_Data,
  IReturn_Data,
  IStock_Data,
} from "../interface/interface.RenderSlideMarket";

export const Data_Stock_Exchange: IStock_Data[] = [
  {
    StockIndex: "VNXALL",
    StockExchange: "HSX",
    className: VNXALL,
  },
  {
    StockIndex: "VNI",
    StockExchange: "HSX",
    className: VNI,
  },
  {
    StockIndex: "VN30",
    StockExchange: "HSX",
    className: VN30,
  },
  {
    StockIndex: "VN100",
    StockExchange: "HSX",
    className: VN100,
  },
  {
    StockIndex: "VNALL",
    StockExchange: "HSX",
    className: VNALL,
  },
  {
    StockIndex: "VNMID",
    StockExchange: "HSX",
    className: VNMID,
  },
  {
    StockIndex: "VNSML",
    StockExchange: "HSX",
    className: VNMSL,
  },
  {
    StockIndex: "HNX",
    StockExchange: "HNX",
    className: HNX,
  },
  {
    StockIndex: "HNX30",
    StockExchange: "HNX",
    className: HNX30,
  },
  {
    StockIndex: "HNXLCAP",
    StockExchange: "HNX",
    className: HNXLCAP,
  },
  {
    StockIndex: "HNXSMCAP",
    StockExchange: "HNX",
    className: HNXSMCAP,
  },
  {
    StockIndex: "HNXFIN",
    StockExchange: "HNX",
    className: HNXFIN,
  },
  {
    StockIndex: "HNXMAN",
    StockExchange: "HNX",
    className: HNXMAN,
  },
  {
    StockIndex: "HNXCON",
    StockExchange: "HNX",
    className: HNXCON,
  },
  {
    StockIndex: "HNXUPCOM",
    StockExchange: "HNX",
    className: UPCOM,
  },
];
export function RenderSlideNarketItem(
  data: IRecieve_Data
): IReturn_Data | string {
  switch (data.name) {
    case "VNXALL":
      return {
        type: data.type.VNXALL,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VNXALL_IndexValue,
        valueChange: data.marketHSX.VNXALL_Change,
        valueChangePercent: data.marketHSX.VNXALL_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VNXALL_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VNXALL_TotalValuesAOM,
        valueUp: data.marketHSX.VNXALL_Up,
        valueCeiling: data.marketHSX.VNXALL_Ceiling,
        valueNoChange: data.marketHSX.VNXALL_NoChange,
        valueDown: data.marketHSX.VNXALL_Down,
        valueFloor: data.marketHSX.VNXALL_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VNI":
      return {
        type: data.type.VNI,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VNI_IndexValue,
        valueChange: data.marketHSX.VNI_Change,
        valueChangePercent: data.marketHSX.VNI_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VNI_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VNI_TotalValuesAOM,
        valueUp: data.marketHSX.VNI_Up,
        valueCeiling: data.marketHSX.VNI_Ceiling,
        valueNoChange: data.marketHSX.VNI_NoChange,
        valueDown: data.marketHSX.VNI_Down,
        valueFloor: data.marketHSX.VNI_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VN30":
      return {
        type: data.type.VN30,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VN30_IndexValue,
        valueChange: data.marketHSX.VN30_Change,
        valueChangePercent: data.marketHSX.VN30_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VN30_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VN30_TotalValuesAOM,
        valueUp: data.marketHSX.VN30_Up,
        valueCeiling: data.marketHSX.VN30_Ceiling,
        valueNoChange: data.marketHSX.VN30_NoChange,
        valueDown: data.marketHSX.VN30_Down,
        valueFloor: data.marketHSX.VN30_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VN100":
      return {
        type: data.type.VN100,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VN100_IndexValue,
        valueChange: data.marketHSX.VN100_Change,
        valueChangePercent: data.marketHSX.VN100_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VN100_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VN100_TotalValuesAOM,
        valueUp: data.marketHSX.VN100_Up,
        valueCeiling: data.marketHSX.VN100_Ceiling,
        valueNoChange: data.marketHSX.VN100_NoChange,
        valueDown: data.marketHSX.VN100_Down,
        valueFloor: data.marketHSX.VN100_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VNALL":
      return {
        type: data.type.VNALL,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VNALL_IndexValue,
        valueChange: data.marketHSX.VNALL_Change,
        valueChangePercent: data.marketHSX.VNALL_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VNALL_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VNALL_TotalValuesAOM,
        valueUp: data.marketHSX.VNALL_Up,
        valueCeiling: data.marketHSX.VNALL_Ceiling,
        valueNoChange: data.marketHSX.VNALL_NoChange,
        valueDown: data.marketHSX.VNALL_Down,
        valueFloor: data.marketHSX.VNALL_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VNMID":
      return {
        type: data.type.VNMID,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VNMID_IndexValue,
        valueChange: data.marketHSX.VNMID_Change,
        valueChangePercent: data.marketHSX.VNMID_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VNMID_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VNMID_TotalValuesAOM,
        valueUp: data.marketHSX.VNMID_Up,
        valueCeiling: data.marketHSX.VNMID_Ceiling,
        valueNoChange: data.marketHSX.VNMID_NoChange,
        valueDown: data.marketHSX.VNMID_Down,
        valueFloor: data.marketHSX.VNMID_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "VNSML":
      return {
        type: data.type.VNSML,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHSX.VNSML_IndexValue,
        valueChange: data.marketHSX.VNSML_Change,
        valueChangePercent: data.marketHSX.VNSML_ChangePercent,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHSX.VNSML_TotalSharesAOM,
        valueTotalValuesAOM: data.marketHSX.VNSML_TotalValuesAOM,
        valueUp: data.marketHSX.VNSML_Up,
        valueCeiling: data.marketHSX.VNSML_Ceiling,
        valueNoChange: data.marketHSX.VNSML_NoChange,
        valueDown: data.marketHSX.VNSML_Down,
        valueFloor: data.marketHSX.VNSML_Floor,
        status: fStatusMarketHSX(data.marketHSX.STAT_ControlCode),
      };
    case "HNX":
      return {
        type: data.type.HNX,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i02_3,
        valueChange: data.marketHNX.i02_5,
        valueChangePercent: data.marketHNX.i02_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i02_7,
        valueTotalValuesAOM: data.marketHNX.i02_14,
        valueUp: data.marketHNX.i02_x251,
        valueCeiling: data.marketHNX.i02_x251c,
        valueNoChange: data.marketHNX.i02_x252,
        valueDown: data.marketHNX.i02_x253,
        valueFloor: data.marketHNX.i02_x253f,
        status: fStatusMarketHNX(data.marketHNX.i02_x336x340),
      };
    case "HNX30":
      return {
        type: data.type.HNX30,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i41_3,
        valueChange: data.marketHNX.i41_5,
        valueChangePercent: data.marketHNX.i41_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i41_7,
        valueTotalValuesAOM: data.marketHNX.i41_14,
        valueUp: data.marketHNX.i41_x251,
        valueCeiling: data.marketHNX.i41_x251c,
        valueNoChange: data.marketHNX.i41_x252,
        valueDown: data.marketHNX.i41_x253,
        valueFloor: data.marketHNX.i41_x253f,
        status: fStatusMarketHNX(data.marketHNX.i41_x336x340),
      };
    case "HNXLCAP":
      return {
        type: data.type.HNXLCAP,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i26_3,
        valueChange: data.marketHNX.i26_5,
        valueChangePercent: data.marketHNX.i26_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i26_7,
        valueTotalValuesAOM: data.marketHNX.i26_14,
        valueUp: data.marketHNX.i26_x251,
        valueCeiling: data.marketHNX.i26_x251c,
        valueNoChange: data.marketHNX.i26_x252,
        valueDown: data.marketHNX.i26_x253,
        valueFloor: data.marketHNX.i26_x253f,
        status: fStatusMarketHNX(data.marketHNX.i26_x336x340),
      };
    case "HNXSMCAP":
      return {
        type: data.type.HNXSMCAP,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i28_3,
        valueChange: data.marketHNX.i28_5,
        valueChangePercent: data.marketHNX.i28_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i28_7,
        valueTotalValuesAOM: data.marketHNX.i28_14,
        valueUp: data.marketHNX.i28_x251,
        valueCeiling: data.marketHNX.i28_x251c,
        valueNoChange: data.marketHNX.i28_x252,
        valueDown: data.marketHNX.i28_x253,
        valueFloor: data.marketHNX.i28_x253f,
        status: fStatusMarketHNX(data.marketHNX.i28_x336x340),
      };
    case "HNXFIN":
      return {
        type: data.type.HNXFIN,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i39_3,
        valueChange: data.marketHNX.i39_5,
        valueChangePercent: data.marketHNX.i39_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i39_7,
        valueTotalValuesAOM: data.marketHNX.i39_14,
        valueUp: data.marketHNX.i39_x251,
        valueCeiling: data.marketHNX.i39_x251c,
        valueNoChange: data.marketHNX.i39_x252,
        valueDown: data.marketHNX.i39_x253,
        valueFloor: data.marketHNX.i39_x253f,
        status: fStatusMarketHNX(data.marketHNX.i39_x336x340),
      };
    case "HNXMAN":
      return {
        type: data.type.HNXMAN,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i310_3,
        valueChange: data.marketHNX.i310_5,
        valueChangePercent: data.marketHNX.i310_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i310_7,
        valueTotalValuesAOM: data.marketHNX.i310_14,
        valueUp: data.marketHNX.i310_x251,
        valueCeiling: data.marketHNX.i310_x251c,
        valueNoChange: data.marketHNX.i310_x252,
        valueDown: data.marketHNX.i310_x253,
        valueFloor: data.marketHNX.i310_x253f,
        status: fStatusMarketHNX(data.marketHNX.i310_x336x340),
      };
    case "HNXCON":
      return {
        type: data.type.HNXCON,
        id: data.id,
        name: data.name,
        san: data.san,
        valueIndexChange: data.marketHNX.i311_3,
        valueChange: data.marketHNX.i311_5,
        valueChangePercent: data.marketHNX.i311_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i311_7,
        valueTotalValuesAOM: data.marketHNX.i311_14,
        valueUp: data.marketHNX.i311_x251,
        valueCeiling: data.marketHNX.i311_x251c,
        valueNoChange: data.marketHNX.i311_x252,
        valueDown: data.marketHNX.i311_x253,
        valueFloor: data.marketHNX.i311_x253f,
        status: fStatusMarketHNX(data.marketHNX.i311_x336x340),
      };
    case "HNXUPCOM":
      return {
        type: data.type.UPCOM,
        id: data.id,
        name: "UPCOM",
        san: data.san,
        valueIndexChange: data.marketHNX.i03_3,
        valueChange: data.marketHNX.i03_5,
        valueChangePercent: data.marketHNX.i03_6,
        visible: data.visible,
        valueTotalSharesAOM: data.marketHNX.i03_7,
        valueTotalValuesAOM: data.marketHNX.i03_14,
        valueUp: data.marketHNX.i03_x251,
        valueCeiling: data.marketHNX.i03_x251c,
        valueNoChange: data.marketHNX.i03_x252,
        valueDown: data.marketHNX.i03_x253,
        valueFloor: data.marketHNX.i03_x253f,
        status: fStatusMarketUPCOM(data.marketHNX.i03_x336x340),
      };
    default:
      return `Something wrong here!!!`
  }
}
