import {
  HNX,
  HNX30,
  HNXCON,
  HNXFIN,
  HNXLCAP,
  HNXMAN,
  HNXSMCAP,
  UPCOM,
  VN100,
  VN30,
  VNALL,
  VNI,
  VNMID,
  VNMSL,
  VNXALL,
} from "../className";
import { ObjectMenuHNX, ObjectMenuHSX } from "../../../models/modelListMenuHSX";
import { ISlideMarket } from "../interface/slidemarket.config";
import {
  fStatusMarketHNX,
  fStatusMarketHSX,
  fStatusMarketUPCOM,
} from "../../../utils/util";
import { IIndex } from "../marketShowSlice";

export const g_ARRAY_CHART_NAME: string[] = [
  "VNXALL",
  "VNI",
  "VN30",
  "VN100",
  "VNALL",
  "VNMID",
  "VNSML",
  "HNX",
  "HNX30",
  "HNXLCAP",
  "HNXSMCAP",
  "HNXFIN",
  "HNXMAN",
  "HNXCON",
  "UPCOM",
];

export function renderSlideMarket(
  type: IIndex,
  name: string,
  valueHSX: ObjectMenuHSX,
  valueHNX: ObjectMenuHNX,
  visible: boolean
) {
  switch (name) {
    case "VNXALL":
      return {
        type: type.VNXALL,
        name: name,
        id: VNXALL,
        valueIndexChange: valueHSX?.VNXALL_IndexValue,
        valueChange: valueHSX?.VNXALL_Change,
        valueChangePercent: valueHSX?.VNXALL_ChangePercent,
        visible,
        valueTotalSharesAOM: valueHSX?.VNXALL_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VNXALL_TotalValuesAOM,
        valueUp: valueHSX?.VNXALL_Up,
        valueCeiling: valueHSX?.VNXALL_Ceiling,
        valueNoChange: valueHSX?.VNXALL_NoChange,
        valueDown: valueHSX?.VNXALL_Down,
        valueFloor: valueHSX?.VNXALL_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VNI":
      return {
        type: type.VNI,
        name: name,
        id: VNI,
        valueIndexChange: valueHSX?.VNI_IndexValue,
        valueChange: valueHSX?.VNI_Change,
        valueChangePercent: valueHSX?.VNI_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VNI_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VNI_TotalValuesAOM,
        valueUp: valueHSX?.VNI_Up,
        valueCeiling: valueHSX?.VNI_Ceiling,
        valueNoChange: valueHSX?.VNI_NoChange,
        valueDown: valueHSX?.VNI_Down,
        valueFloor: valueHSX?.VNI_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VN30":
      return {
        type: type.VN30,
        name: name,
        id: VN30,
        valueIndexChange: valueHSX?.VN30_IndexValue,
        valueChange: valueHSX?.VN30_Change,
        valueChangePercent: valueHSX?.VN30_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VN30_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VN30_TotalValuesAOM,
        valueUp: valueHSX?.VN30_Up,
        valueCeiling: valueHSX?.VN30_Ceiling,
        valueNoChange: valueHSX?.VN30_NoChange,
        valueDown: valueHSX?.VN30_Down,
        valueFloor: valueHSX?.VN30_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VN100":
      return {
        type: type.VN100,
        name: name,
        id: VN100,
        valueIndexChange: valueHSX?.VN100_IndexValue,
        valueChange: valueHSX?.VN100_Change,
        valueChangePercent: valueHSX?.VN100_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VN100_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VN100_TotalValuesAOM,
        valueUp: valueHSX?.VN100_Up,
        valueCeiling: valueHSX?.VN100_Ceiling,
        valueNoChange: valueHSX?.VN100_NoChange,
        valueDown: valueHSX?.VN100_Down,
        valueFloor: valueHSX?.VN100_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VNALL":
      return {
        type: type.VNALL,
        name: name,
        id: VNALL,
        valueIndexChange: valueHSX?.VNALL_IndexValue,
        valueChange: valueHSX?.VNALL_Change,
        valueChangePercent: valueHSX?.VNALL_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VNALL_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VNALL_TotalValuesAOM,
        valueUp: valueHSX?.VNALL_Up,
        valueCeiling: valueHSX?.VNALL_Ceiling,
        valueNoChange: valueHSX?.VNALL_NoChange,
        valueDown: valueHSX?.VNALL_Down,
        valueFloor: valueHSX?.VNALL_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VNMID":
      return {
        type: type.VNMID,
        name: name,
        id: VNMID,
        valueIndexChange: valueHSX?.VNMID_IndexValue,
        valueChange: valueHSX?.VNMID_Change,
        valueChangePercent: valueHSX?.VNMID_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VNMID_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VNMID_TotalValuesAOM,
        valueUp: valueHSX?.VNMID_Up,
        valueCeiling: valueHSX?.VNMID_Ceiling,
        valueNoChange: valueHSX?.VNMID_NoChange,
        valueDown: valueHSX?.VNMID_Down,
        valueFloor: valueHSX?.VNMID_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "VNSML":
      return {
        type: type.VNSML,
        name: name,
        id: VNMSL,
        valueIndexChange: valueHSX?.VNSML_IndexValue,
        valueChange: valueHSX?.VNSML_Change,
        valueChangePercent: valueHSX?.VNSML_ChangePercent,
        visible: visible,
        valueTotalSharesAOM: valueHSX?.VNSML_TotalSharesAOM,
        valueTotalValuesAOM: valueHSX?.VNSML_TotalValuesAOM,
        valueUp: valueHSX?.VNSML_Up,
        valueCeiling: valueHSX?.VNSML_Ceiling,
        valueNoChange: valueHSX?.VNSML_NoChange,
        valueDown: valueHSX?.VNSML_Down,
        valueFloor: valueHSX?.VNSML_Floor,
        status: fStatusMarketHSX(valueHSX?.STAT_ControlCode),
        san: "HSX",
      };
    case "HNX":
      return {
        type: type.HNX,
        name: name,
        id: HNX,
        valueIndexChange: valueHNX?.i02_3,
        valueChange: valueHNX?.i02_5,
        valueChangePercent: valueHNX?.i02_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i02_7,
        valueTotalValuesAOM: valueHNX?.i02_14,
        valueUp: valueHNX?.i02_x251,
        valueCeiling: valueHNX?.i02_x251c,
        valueNoChange: valueHNX?.i02_x252,
        valueDown: valueHNX?.i02_x253,
        valueFloor: valueHNX?.i02_x253f,
        status: fStatusMarketHNX(valueHNX?.i02_x336x340),
        san: "HNX",
      };
    case "HNX30":
      return {
        type: type.HNX30,
        name: name,
        id: HNX30,
        valueIndexChange: valueHNX?.i41_3,
        valueChange: valueHNX?.i41_5,
        valueChangePercent: valueHNX?.i41_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i41_7,
        valueTotalValuesAOM: valueHNX?.i41_14,
        valueUp: valueHNX?.i41_x251,
        valueCeiling: valueHNX?.i41_x251c,
        valueNoChange: valueHNX?.i41_x252,
        valueDown: valueHNX?.i41_x253,
        valueFloor: valueHNX?.i41_x253f,
        status: fStatusMarketHNX(valueHNX?.i41_x336x340),
        san: "HNX",
      };
    case "HNXLCAP":
      return {
        type: type.HNXLCAP,
        name: name,
        id: HNXLCAP,
        valueIndexChange: valueHNX?.i26_3,
        valueChange: valueHNX?.i26_5,
        valueChangePercent: valueHNX?.i26_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i26_7,
        valueTotalValuesAOM: valueHNX?.i26_14,
        valueUp: valueHNX?.i26_x251,
        valueCeiling: valueHNX?.i26_x251c,
        valueNoChange: valueHNX?.i26_x252,
        valueDown: valueHNX?.i26_x253,
        valueFloor: valueHNX?.i26_x253f,
        status: fStatusMarketHNX(valueHNX?.i26_x336x340),
        san: "HNX",
      };
    case "HNXSMCAP":
      return {
        type: type.HNXSMCAP,
        name: name,
        id: HNXSMCAP,
        valueIndexChange: valueHNX?.i28_3,
        valueChange: valueHNX?.i28_5,
        valueChangePercent: valueHNX?.i28_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i28_7,
        valueTotalValuesAOM: valueHNX?.i28_14,
        valueUp: valueHNX?.i28_x251,
        valueCeiling: valueHNX?.i28_x251c,
        valueNoChange: valueHNX?.i28_x252,
        valueDown: valueHNX?.i28_x253,
        valueFloor: valueHNX?.i28_x253f,
        status: fStatusMarketHNX(valueHNX?.i28_x336x340),
        san: "HNX",
      };
    case "HNXFIN":
      return {
        type: type.HNXFIN,
        name: name,
        id: HNXFIN,
        valueIndexChange: valueHNX?.i39_3,
        valueChange: valueHNX?.i39_5,
        valueChangePercent: valueHNX?.i39_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i39_7,
        valueTotalValuesAOM: valueHNX?.i39_14,
        valueUp: valueHNX?.i39_x251,
        valueCeiling: valueHNX?.i39_x251c,
        valueNoChange: valueHNX?.i39_x252,
        valueDown: valueHNX?.i39_x253,
        valueFloor: valueHNX?.i39_x253f,
        status: fStatusMarketHNX(valueHNX?.i39_x336x340),
        san: "HNX",
      };
    case "HNXMAN":
      return {
        type: type.HNXMAN,
        name: name,
        id: HNXMAN,
        valueIndexChange: valueHNX?.i310_3,
        valueChange: valueHNX?.i310_5,
        valueChangePercent: valueHNX?.i310_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i310_7,
        valueTotalValuesAOM: valueHNX?.i310_14,
        valueUp: valueHNX?.i310_x251,
        valueCeiling: valueHNX?.i310_x251c,
        valueNoChange: valueHNX?.i310_x252,
        valueDown: valueHNX?.i310_x253,
        valueFloor: valueHNX?.i310_x253f,
        status: fStatusMarketHNX(valueHNX?.i310_x336x340),
        san: "HNX",
      };
    case "HNXCON":
      return {
        type: type.HNXCON,
        name: name,
        id: HNXCON,
        valueIndexChange: valueHNX?.i311_3,
        valueChange: valueHNX?.i311_5,
        valueChangePercent: valueHNX?.i311_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i311_7,
        valueTotalValuesAOM: valueHNX?.i311_14,
        valueUp: valueHNX?.i311_x251,
        valueCeiling: valueHNX?.i311_x251c,
        valueNoChange: valueHNX?.i311_x252,
        valueDown: valueHNX?.i311_x253,
        valueFloor: valueHNX?.i311_x253f,
        status: fStatusMarketHNX(valueHNX?.i311_x336x340),
        san: "HNX",
      };
    case "UPCOM":
      return {
        type: type.UPCOM,
        name: name,
        id: UPCOM,
        valueIndexChange: valueHNX?.i03_3,
        valueChange: valueHNX?.i03_5,
        valueChangePercent: valueHNX?.i03_6,
        visible: visible,
        valueTotalSharesAOM: valueHNX?.i03_7,
        valueTotalValuesAOM: valueHNX?.i03_14,
        valueUp: valueHNX?.i03_x251,
        valueCeiling: valueHNX?.i03_x251c,
        valueNoChange: valueHNX?.i03_x252,
        valueDown: valueHNX?.i03_x253,
        valueFloor: valueHNX?.i03_x253f,
        status: fStatusMarketUPCOM(valueHNX?.i03_x336x340),
        san: "HNX",
      };
  }
}
